#pragma once

#include <cmath>
#include <ostream>
#include <functional>

#ifndef VELOCITY_MATH_ERROR
    #include <stdexcept>
    #define VELOCITY_MATH_ERROR(msg) throw std::runtime_error(msg)
#endif

#ifndef VELOCITY_MATH_EPSILON
    #define VELOCITY_MATH_EPSILON 1e-6f
#endif

#define VELOCITY_MATH_SWIZZLE_VECTOR2_ENTRY(A, B) \
    constexpr Vector2 A ## B() const { \
        return Vector2{this->A, this->B}; \
    }

#define VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(A, B, C) \
    constexpr Vector3 A ## B ## C() const { \
        return Vector3{this->A, this->B, this->C}; \
    }

#define VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, B, C, D) \
    constexpr Vector4 A ## B ## C ## D() const { \
        return Vector4{this->A, this->B, this->C, this->D}; \
    }

#define VELOCITY_MATH_GEN_VECTOR2_FROM_VECTOR2(A, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR2_ENTRY(A, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR2_ENTRY(A, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR2_ENTRY(B, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR2_ENTRY(B, B)

#define VELOCITY_MATH_GEN_VECTOR2_FROM_VECTOR3(A, B, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR2_ENTRY(A, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR2_ENTRY(A, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR2_ENTRY(A, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR2_ENTRY(B, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR2_ENTRY(B, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR2_ENTRY(B, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR2_ENTRY(C, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR2_ENTRY(C, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR2_ENTRY(C, C)

#define VELOCITY_MATH_GEN_VECTOR2_FROM_VECTOR4(A, B, C, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR2_ENTRY(A, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR2_ENTRY(A, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR2_ENTRY(A, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR2_ENTRY(A, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR2_ENTRY(B, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR2_ENTRY(B, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR2_ENTRY(B, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR2_ENTRY(B, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR2_ENTRY(C, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR2_ENTRY(C, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR2_ENTRY(C, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR2_ENTRY(C, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR2_ENTRY(D, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR2_ENTRY(D, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR2_ENTRY(D, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR2_ENTRY(D, D)

#define VELOCITY_MATH_GEN_VECTOR3_FROM_VECTOR3(A, B, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(A, A, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(A, A, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(A, A, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(A, B, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(A, B, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(A, B, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(A, C, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(A, C, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(A, C, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(B, A, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(B, A, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(B, A, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(B, B, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(B, B, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(B, B, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(B, C, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(B, C, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(B, C, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(C, A, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(C, A, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(C, A, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(C, B, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(C, B, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(C, B, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(C, C, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(C, C, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(C, C, C) \

#define VELOCITY_MATH_GEN_VECTOR3_FROM_VECTOR4(A, B, C, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(A, A, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(A, A, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(A, A, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(A, A, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(A, B, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(A, B, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(A, B, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(A, B, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(A, C, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(A, C, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(A, C, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(A, C, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(A, D, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(A, D, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(A, D, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(A, D, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(B, A, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(B, A, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(B, A, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(B, A, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(B, B, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(B, B, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(B, B, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(B, B, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(B, C, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(B, C, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(B, C, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(B, C, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(B, D, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(B, D, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(B, D, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(B, D, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(C, A, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(C, A, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(C, A, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(C, A, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(C, B, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(C, B, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(C, B, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(C, B, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(C, C, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(C, C, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(C, C, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(C, C, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(C, D, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(C, D, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(C, D, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(C, D, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(D, A, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(D, A, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(D, A, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(D, A, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(D, B, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(D, B, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(D, B, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(D, B, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(D, C, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(D, C, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(D, C, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(D, C, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(D, D, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(D, D, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(D, D, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR3_ENTRY(D, D, D)

#define VELOCITY_MATH_GEN_VECTOR4_FROM_VECTOR4(A, B, C, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, A, A, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, A, A, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, A, A, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, A, A, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, A, B, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, A, B, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, A, B, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, A, B, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, A, C, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, A, C, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, A, C, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, A, C, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, A, D, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, A, D, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, A, D, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, A, D, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, B, A, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, B, A, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, B, A, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, B, A, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, B, B, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, B, B, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, B, B, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, B, B, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, B, C, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, B, C, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, B, C, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, B, C, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, B, D, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, B, D, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, B, D, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, B, D, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, C, A, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, C, A, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, C, A, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, C, A, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, C, B, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, C, B, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, C, B, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, C, B, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, C, C, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, C, C, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, C, C, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, C, C, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, C, D, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, C, D, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, C, D, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, C, D, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, D, A, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, D, A, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, D, A, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, D, A, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, D, B, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, D, B, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, D, B, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, D, B, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, D, C, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, D, C, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, D, C, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, D, C, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, D, D, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, D, D, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, D, D, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(A, D, D, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, A, A, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, A, A, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, A, A, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, A, A, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, A, B, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, A, B, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, A, B, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, A, B, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, A, C, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, A, C, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, A, C, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, A, C, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, A, D, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, A, D, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, A, D, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, A, D, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, B, A, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, B, A, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, B, A, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, B, A, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, B, B, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, B, B, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, B, B, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, B, B, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, B, C, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, B, C, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, B, C, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, B, C, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, B, D, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, B, D, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, B, D, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, B, D, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, C, A, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, C, A, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, C, A, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, C, A, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, C, B, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, C, B, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, C, B, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, C, B, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, C, C, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, C, C, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, C, C, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, C, C, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, C, D, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, C, D, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, C, D, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, C, D, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, D, A, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, D, A, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, D, A, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, D, A, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, D, B, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, D, B, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, D, B, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, D, B, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, D, C, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, D, C, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, D, C, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, D, C, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, D, D, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, D, D, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, D, D, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(B, D, D, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, A, A, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, A, A, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, A, A, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, A, A, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, A, B, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, A, B, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, A, B, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, A, B, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, A, C, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, A, C, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, A, C, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, A, C, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, A, D, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, A, D, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, A, D, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, A, D, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, B, A, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, B, A, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, B, A, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, B, A, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, B, B, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, B, B, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, B, B, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, B, B, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, B, C, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, B, C, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, B, C, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, B, C, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, B, D, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, B, D, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, B, D, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, B, D, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, C, A, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, C, A, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, C, A, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, C, A, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, C, B, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, C, B, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, C, B, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, C, B, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, C, C, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, C, C, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, C, C, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, C, C, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, C, D, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, C, D, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, C, D, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, C, D, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, D, A, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, D, A, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, D, A, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, D, A, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, D, B, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, D, B, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, D, B, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, D, B, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, D, C, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, D, C, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, D, C, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, D, C, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, D, D, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, D, D, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, D, D, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(C, D, D, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, A, A, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, A, A, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, A, A, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, A, A, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, A, B, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, A, B, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, A, B, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, A, B, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, A, C, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, A, C, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, A, C, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, A, C, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, A, D, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, A, D, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, A, D, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, A, D, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, B, A, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, B, A, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, B, A, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, B, A, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, B, B, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, B, B, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, B, B, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, B, B, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, B, C, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, B, C, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, B, C, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, B, C, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, B, D, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, B, D, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, B, D, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, B, D, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, C, A, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, C, A, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, C, A, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, C, A, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, C, B, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, C, B, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, C, B, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, C, B, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, C, C, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, C, C, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, C, C, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, C, C, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, C, D, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, C, D, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, C, D, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, C, D, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, D, A, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, D, A, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, D, A, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, D, A, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, D, B, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, D, B, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, D, B, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, D, B, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, D, C, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, D, C, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, D, C, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, D, C, D) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, D, D, A) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, D, D, B) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, D, D, C) \
    VELOCITY_MATH_SWIZZLE_VECTOR4_ENTRY(D, D, D, D)

#define VELOCITY_MATH_SWIZZLE_VECTOR2 \
    VELOCITY_MATH_GEN_VECTOR2_FROM_VECTOR2(x, y) \
    VELOCITY_MATH_GEN_VECTOR2_FROM_VECTOR2(r, g) \
    VELOCITY_MATH_GEN_VECTOR2_FROM_VECTOR2(s, t)

#define VELOCITY_MATH_SWIZZLE_VECTOR3 \
    VELOCITY_MATH_GEN_VECTOR2_FROM_VECTOR3(x, y, z) \
    VELOCITY_MATH_GEN_VECTOR2_FROM_VECTOR3(r, g, b) \
    VELOCITY_MATH_GEN_VECTOR2_FROM_VECTOR3(s, t, p) \
    VELOCITY_MATH_GEN_VECTOR3_FROM_VECTOR3(x, y, z) \
    VELOCITY_MATH_GEN_VECTOR3_FROM_VECTOR3(r, g, b) \
    VELOCITY_MATH_GEN_VECTOR3_FROM_VECTOR3(s, t, p)

#define VELOCITY_MATH_SWIZZLE_VECTOR4 \
    VELOCITY_MATH_GEN_VECTOR2_FROM_VECTOR4(x, y, z, w) \
    VELOCITY_MATH_GEN_VECTOR2_FROM_VECTOR4(r, g, b, a) \
    VELOCITY_MATH_GEN_VECTOR2_FROM_VECTOR4(s, t, p, q) \
    VELOCITY_MATH_GEN_VECTOR3_FROM_VECTOR4(x, y, z, w) \
    VELOCITY_MATH_GEN_VECTOR3_FROM_VECTOR4(r, g, b, a) \
    VELOCITY_MATH_GEN_VECTOR3_FROM_VECTOR4(s, t, p, q) \
    VELOCITY_MATH_GEN_VECTOR4_FROM_VECTOR4(x, y, z, w) \
    VELOCITY_MATH_GEN_VECTOR4_FROM_VECTOR4(r, g, b, a) \
    VELOCITY_MATH_GEN_VECTOR4_FROM_VECTOR4(s, t, p, q)